services:
  - type: web
    name: bucknell-flask-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free

cronJobs:
  - name: daily-scraper
    schedule: "0 8 * * *"  # Every day at 8:00 AM UTC
    command: "python scraper.py"
